### ISSUE TITLE
Multiple sections with different types

### ISSUE THREAD

**Issue by hashemp206** [ra1028/DifferenceKit#12] opened 2018-08-24 05:47 UTC
I want my collection handle multiple sections with different Items.

Section1: Int
Section2: String

how is it possible?
you have showcased one section with multiple items with `AnyDifferentiable`, but what about multiple sections with multiple types.

**Comment by ra1028** [comment] 2018-08-24 08:06
Hi @hashemp206 

To put multiple types into the collection, you must be erase the type of elements.
You can use `AnyDifferentiable` as you say.
for example:
```swift
extension Int: Differentiable {}
extension String: Differentiable {}

enum ID: Differentiable {
    case a, b
}

let sectionA = ArraySection<ID, AnyDifferentiable>(model: .a, elements: [
    AnyDifferentiable(0),
    AnyDifferentiable(1),
    AnyDifferentiable(2)]
let sectionB = ArraySection<ID, AnyDifferentiable>(model: .a, elements: [
    AnyDifferentiable("foo"),
    AnyDifferentiable("bar"),
    AnyDifferentiable("baz")]
)

let data: [ArraySection<ID, AnyDifferentiable>] = [sectionA, sectionB]
```

In the same way,  you can use`AnyDiffetiable` to erasing the type of `ArraySection.Model`.
```swift
typealias AnyArraySection =  ArraySection<AnyDifferentiable, AnyDifferentiable>

let sectionA = AnyArraySection(model: AnyDifferentiable(0), elements: [
    AnyDifferentiable(0),
    AnyDifferentiable(1),
    AnyDifferentiable(2)]
let sectionB = AnyArraySection(model: AnyDifferentiable("B"), elements: [
    AnyDifferentiable("foo"),
    AnyDifferentiable("bar"),
    AnyDifferentiable("baz")]
)

let data: [AnyArraySection] = [sectionA, sectionB]
```

If you are asking about multiple types conforming to `DifferentiableSection`, it needs the type-erased `DifferentiableSection`.
But, it's not built into DifferenceKit.
Do you need it?

**Comment by Sameesunkaria** [comment] 2018-08-25 10:49
@ra1028 's answer is probably the way to go. But one more approach is to use an enum with an associated value. The only catch is that you would have to conform that enum to `Hashable` on your own.

```
enum DataModel: Equatable, Differentiable {
    case int(Int)
    case string(String)
}

extension DataModel: Hashable {
    // Add your own implementation
}
```

**Comment by hashemp206** [comment] 2018-08-25 18:27
thanks for quick response and sorry for my late answer
when I define sectionA or B complier complains about:

`Generic parameter 'D' could not be inferred`

is it possible to change `AnyDifferentiable ` to be type safe?

<img width="721" alt="screen shot 2018-08-25 at 10 55 45 pm" src="https://user-images.githubusercontent.com/3206748/44621358-34526a80-a8ba-11e8-9bb5-863f98a47149.png">

**Comment by ra1028** [comment] 2018-08-26 12:50
@hashemp206 
hmm.
I tried the same code, but it worked correctly.
It's probably not the cause of the compilation error, but please make sure that the Int type conforms to the `Differentiable` in your project.
If that does not work, please tell me the Swift and Xcode version.
btw, `Section` is now renamed to `ArraySection`, please update the DifferenceKit.

**Comment by hashemp206** [comment] 2018-08-26 18:39
Using Swift 4.2 and `DifferenceKit` '0.5.1', I pasted your code!

**Comment by hashemp206** [comment] 2018-08-26 18:55
It was because I had to define an extension for `Int` to conform to `Differentiable`
please create a file name `Foundation+ Differentiable` and add default extensions

**Comment by ra1028** [comment] 2018-08-26 19:09
@hashemp206 
I don't prefer that.
I think that to implement on your project is better way.
Since there is a default implementation for `Differentiable` to Hashable and Equatable conforming types, you can easily make it conform to `Differentiable` as follows.
```swift
extension Int: Differentiable {}
extension String: Differentiable {}
```
See [here](https://github.com/ra1028/DifferenceKit/blob/master/Sources/Differentiable.swift) for details.

**Comment by ra1028** [comment] 2018-08-27 05:53
@hashemp206 

> if I insert a same section (same hash value) multiple times, StagedChangeSet always says a section inserted. But I think StagedChangeSet should ignore the same sections

Using `Array.insert` obviously the section will be inserted with animation.
What you want to say is the elements replacement as follows?
```swift
private var sections: [ArraySection<ListStores.Section, AnyDifferentiable>] = [
    sectionCafeteria(model: .cafeterias, elements: []),
    sectionSpinner(...)
]

var cafeterias = [ListStores.FetchCafeterias.ViewModel.DisplayStore]() {
    didSet {
        sectionInput[0].elements = cafeterias.map(AnyDifferentiable.init)
    }
}
```

> the next thing is possible AnyDifferentiable to be type safe? I always have to cast base object to target type

Can not put multiple types in an array in Swift.
You can implement using enum proposed by @Sameesunkaria in your case.

**Closed** 2018-08-27 07:56 UTC
